# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-27 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('porcentaje', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
