# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-26 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='video',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
