# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-27 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupon',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='cupon',
            name='porcentaje',
        ),
        migrations.AlterField(
            model_name='cupon',
            name='nombre',
            field=models.TextField(),
        ),
    ]
