# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='eventos.Evento'),
        ),
    ]
