# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 18:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0003_auto_20160411_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivos', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='evento',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='aplicant',
            name='evento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento'),
        ),
        migrations.AddField(
            model_name='aplicant',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicantes', to=settings.AUTH_USER_MODEL),
        ),
    ]
