# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_auto_20160512_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='slug',
            field=models.SlugField(max_length=60),
        ),
    ]
