# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_auto_20160512_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='boton',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
