# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_auto_20160512_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
