# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_auto_20160512_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='precio',
            field=models.CharField(max_length=10),
        ),
    ]
