# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_auto_20160512_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicant',
            name='beca',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='aplicant',
            name='tipo',
            field=models.CharField(choices=[('Beca 20%', 'Beca 20%'), ('Beca 50%', 'Beca 50%')], default='Beca 20%', max_length=50),
        ),
    ]
