# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_auto_20160512_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicant',
            name='porque',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aplicant',
            name='beca',
            field=models.BooleanField(choices=[(True, 'Si la necesito'), (False, 'No, que la aproveche alguien más')], default=False),
        ),
    ]
