# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_auto_20160512_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicant',
            name='tipo',
            field=models.CharField(choices=[('Beca 20%', 'Beca 20%'), ('Beca 50%', 'Beca 50%')], default=None, max_length=50),
        ),
    ]
