# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_auto_20160512_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicant',
            name='tel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='aplicant',
            name='beca',
            field=models.BooleanField(choices=[(True, 'Si la necesito'), (False, 'No, que la aproveche alguien más')], default='Beca 20%'),
        ),
        migrations.AlterField(
            model_name='aplicant',
            name='motivos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
