# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0016_auto_20160512_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicant',
            name='beca',
            field=models.BooleanField(choices=[(True, 'Si la necesito'), (False, 'No, que la aproveche alguien más')], default=False),
        ),
        migrations.AlterField(
            model_name='aplicant',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Beca 20%', 'Beca 20%'), ('Beca 50%', 'Beca 50%')], default='Beca 20%', max_length=50, null=True),
        ),
    ]
