# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0017_auto_20160523_0034'),
        ('eventos', '0017_auto_20160525_0854'),
    ]

    operations = [
    ]
