# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-09 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0018_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, choices=[('enero', 'Enero'), ('febrero', 'Febrero')], max_length=140, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dia',
            name='mes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Mes'),
        ),
    ]
