# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-10 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0019_auto_20160608_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicant',
            name='fecha',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
