# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-27 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0020_aplicant_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicant',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
