# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-27 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0021_aplicant_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicant',
            name='contactado',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aplicant',
            name='inscrito',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aplicant',
            name='pago',
            field=models.NullBooleanField(default=False),
        ),
    ]
