# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-27 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0022_auto_20160627_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicant',
            name='notas',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
