# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-27 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0023_auto_20160627_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicant',
            name='fecha_de_contacto',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='aplicant',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Beca 20%', 'Beca 20%'), ('Beca 50%', 'Beca 50%'), ('Beca 80%', 'Beca 80%'), ('Beca 100%', 'Beca 100%')], default='Beca 20%', max_length=50, null=True),
        ),
    ]
