# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-27 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0024_auto_20160627_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicant',
            name='contactado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aplicant',
            name='fecha_de_contacto',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
