# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-23 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
