# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ide',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
