# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-24 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applys', '0003_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='beca',
            field=models.CharField(default='no', max_length=2),
        ),
    ]
