# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-08 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applys', '0004_auto_20170224_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='fecha',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
